services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    image: razegold/task-trackeer:staging
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file:
      - .env.staging
    networks:
      - task-trackeer-network-staging

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_trackeer_staging
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - task-trackeer-network-staging

volumes:
  postgres_data_staging:

networks:
  task-trackeer-network-staging:
    name: task-trackeer-network-staging
    driver: bridge
