name: Test Docker Login

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  test-docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Test login
        run: |
          echo "Docker login successful!"
          docker info
