name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test || true
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: razegold/task-trackeer:latest,razegold/task-trackeer:${{ github.sha }}

      - name: Build staging Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: razegold/task-trackeer:staging

      - name: Build production Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: razegold/task-trackeer:production